server:
    port: 6100
    error:
        include-stacktrace: never

spring:
    application:
      name: door-api
    cloud:
        consul:
        host: localhost
        port: 8500
        failFast: false