server:
    port: 9080

spring:
    application:
        name: gateway-service
    cloud:
        consul:
            host: 192.168.0.2
            port: 8500
        gateway:
            discovery:
                locator:
                    enabled: true
                routes:
                    - id: localhost-docker
                      uri: 192.168.0.2:9080

logging.level.com.netflix: DEBUG

management:
    security:
        enabled: false